### ISSUE TITLE
Not working login to VK from aws. 

### ISSUE THREAD

**Issue by EvgenyKravchenko** [stevebest/passport-vkontakte#11]
Hi, 
could you please help me with my issue? 

Now I'm working on login through VK using passport-vkontakte. On my local machine all working well. 
In vk app settings "Site address": "http://localhost:1337", 
callbackUrl is "http://localhost:1337/auth/vkontakte/callback". 

If I move my app to amazon server, login is broken. 
"Site address": "http://my-amazon-domain.tk:1337"
callbackUrl: "http://my-amazon-domain.tk:1337/auth/vkontakte/callback"

When I make attempt to login, I received exception 
![error](https://f.cloud.github.com/assets/1778432/1995749/bcb7b260-8509-11e3-94dc-1d223eb866f0.png)

It's some strange exception, and I can't find possibility to fix them.
Maybe you have some suggestions for resolving this problem?

**Comment by vodolaz095** [comment]
>as standalone application, but as web-application. This helped me.
+1

**Comment by Radren** [comment]
"not as standalone application, but as web-application" - work for my case

**Comment by Yashko** [comment]
its vk security check, if you login from unusual place, it can ask to type phone number of account to verify. you can use https://github.com/Yashko/vk-validation-node (instructions in russian)
