### ISSUE TITLE
Don't return user email when app has permission "email"

### ISSUE THREAD

**Issue by arazumoff** [stevebest/passport-vkontakte#13]
Don't return user email when app has permission "email" with get access_token

**Comment by ArtemKolodko** [comment]
Thank you! It works

**Comment by whitecolor** [comment]
@ArtemKolodko BTW vk.com is still some times may not return email (for unknown reason), so you should handle this situation.

**Comment by ArtemKolodko** [comment]
@whitecolor maybe, it happens when VK user use cellphone number for login only? VK supports cellphone number or email as username

**Comment by whitecolor** [comment]
@ArtemKolodko yeah, it seems you are right.
