### ISSUE TITLE
Unable to get user's email

### ISSUE THREAD

**Issue by skotchio** [stevebest/passport-vkontakte#15]
At now Vkontakte allows to get user's email via specifying `scope: ['email']` parameter:

```
app.get('/auth/vkontakte',
  passport.authenticate('vkontakte', scope: ['email']),
  function(req, res){
    // The request will be redirected to vk.com for authentication, so
    // this function will not be called.
});
```

But unfortunately I don't get this one:

```
passport.use(new VkontakteStrategy({
    clientID: /* clientID */,
    clientSecret: /* clientSecret */,
    callbackURL:  /* callbackURL*/
},
function(token, refreshToken, profile, done) {
      console.log(profile.email) // undefined;
});
```

What I'm doing wrong?

**Comment by ekubyshin** [comment]
look for this lines of codes: https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L192, so you must provide function with 5 arguments, and you can get email in params argument.
