### ISSUE TITLE
Передача email адреса!

### ISSUE THREAD

**Issue by retyui** [stevebest/passport-vkontakte#16]
Если мы передаем 
passport.authenticate('vk',{cope: ['email']})
то эмайл возвращается всместе с access_token, а не при запросе user.get.
и в дальнейшем теряется, на выходе мы получаем профайл без эмайла.
Пофикстите пожалуйста или я, что то не так делаю?
===========================================
![Промежуточный запрос](http://cs625427.vk.me/v625427414/20705/4T0bCpWLmIo.jpg)
![Результат](http://cs625427.vk.me/v625427414/206fc/ZwyFlBh8VUQ.jpg)

**Comment by stevebest** [comment]
Насколько я помню, вконтактик так устроен и ничего с этим поделать нельзя.

Стоит еще учесть, что некоторые пользователи регистрируются в вк по номеру
телефона, и у них в этом случае вообще нет емейла.
11 марта 2015 г. 6:25 пользователь "retyui" <notifications@github.com>
написал:

**Comment by retyui** [comment]
ВК не отдает телефоны. ВК заставляет привязывать мыло к учеткам созданым по номеру тел.
Но не исключено и отсуттвие.
сделал для себя мини фикс:


![Фик](http://cs625427.vk.me/v625427414/20869/ijW3j81j8Ug.jpg)

**Comment by ekubyshin** [comment]
вконтакте отдает email, если пользователь разрешил это. passport все прекрасно обрабатывает, я тут порылся и продебажил исходники вообщем смотри https://github.com/jaredhanson/passport-oauth2/blob/master/lib/strategy.js#L192, тебе надо передать callback с 5 параметрами, тогда тебе в params придет сырой ответ от вк при получении токена.

**Comment by barinbritva** [comment]
Очень странно, что стратегия не берёт на себя объединение этих данных. Я конечно понимаю, что может это ВК странно поступают не возвращая email в профиле. Но в итоге после авторизации я ожидаю в профайле увидеть email, а его нет.
И в [доке](https://github.com/stevebest/passport-vkontakte#profile-fields) об этой особенности не написано.
@ekubyshin, спасибо за воркэраунд.
