### ISSUE TITLE
Добавить require к примерам кода на GitHub

### ISSUE THREAD

**Issue by MaxYari** [stevebest/passport-vkontakte#20]
Если не слишком лениво добавьте способ объявления VKontakteStrategy к примерам во избежания недопониманий.
Имею ввиду строчку вроде
 var VKontakteStrategy = require('passport-vkontakte').Strategy; (если код по большей части форк фб аналога).

**Comment by alexzaitsev** [comment]
+1

**Comment by maxkoryukov** [comment]
fixed in #30
