### ISSUE TITLE
504 gateway time-out

### ISSUE THREAD

**Issue by YanaSavchenko** [stevebest/passport-vkontakte#22]
Ошибка вылетает раз в 10-15 попыток авторизации. Проблема не в провайдере - пробовалось из разных городов и разных стран. Скорее всего, это проблема самого ВК. Но, возможно, посоветуете какое-то решение. Или чтоб сам пасспорт как-то реагировал на это

**Comment by MonoStas** [comment]
Это либо вк, либо (более вероятно) у вас на машине памяти и прочей мощи не хватает, паспорт тут не при чём. Попробуйте ещё серверные настройки подкрутить. Вот для nginx
http://stackoverflow.com/questions/21994758/increase-buffer-timeout-size-on-nginx

**Comment by YanaSavchenko** [comment]
Спасибо. Попробую

**Comment by maxkoryukov** [comment]
@YanaSavchenko , probably, this issue is solved and can be closed :wink:

**Comment by YanaSavchenko** [comment]
Sorry, totally forgot about that
