### ISSUE TITLE
500 on access_denied

### ISSUE THREAD

**Issue by iliakan** [stevebest/passport-vkontakte#26]
In `strategy.js` line 81:
```js
return this.error(new VkontakteAuthorizationError(req.query.error_description, req.query.error, req.query.error_reason));
```

Please fix, should be `this.fail` for access denied, because `this.error` is meant for an "internal error while performing authentication".

That automatically resolves the issue with 500 on access denied.

**Comment by sergey-zero** [comment]
+1 ЭТОМУ НЕДОРАВЗИТОМУ ВИДАТЬ ПОХУЙ ВООБЩЕ. ПУСТЬ НАХУЙ УДАЛЯЕТ ЭТО ГАВНО С NPM МЫ НОРМ ЗАЛЬЁМ

**Comment by stevebest** [comment]
@iliakan Ilya, I accept PRs from people who can behave. :)

**Comment by iliakan** [comment]
That comment wasn't mine.
