### ISSUE TITLE
Getting access for wall.post method

### ISSUE THREAD

**Issue by vadimk-design** [stevebest/passport-vkontakte#27]
Thanks for this library!
Can I get access to wall.post (https://vk.com/dev/wall.post) method with this library?

**Comment by stevebest** [comment]
No, this lib is only for authentication. It allows you to implement a "Login using VK" on your website or in your app - and that's it.

But I've got [stevebest/node-vkontakte](https://github.com/stevebest/node-vkontakte) library for accessing the VK API. Once you've got the user to log in and get his access token, you can post on their wall, list their friends, etc. But you have to [ask a user for permission](https://github.com/stevebest/passport-vkontakte#extended-permissions) to do that, and they have to approve, of course.

Hope that helps!
