### ISSUE TITLE
Отсутствуют указанные права после авторизации

### ISSUE THREAD

**Issue by Qlipoth** [stevebest/passport-vkontakte#29]
Приветствую. Проблема следующая: после выполнения photos.getWallUploadServer в колбек постоянно приходит ошибка Access denied: no access to call this method' ? в scope при авторизации указал groups. access_token есть.

**Comment by stevebest** [comment]
Not everyone using this module and watching this repo speaks Russian, even though we both do. :)

Make sure your `scope` includes the right values for VK API methods you want to call. [photos.getWallUploadServer](https://new.vk.com/dev/photos.getWallUploadServer) requires **photos** permission.

**Comment by Qlipoth** [comment]
I've added that permision to the scope, but nothing changed. Do i need new access_token?

**Comment by stevebest** [comment]
I am not sure if you try to reuse the token that was issued before you requested the needed scope, but if you do then yes, you need a new token.

VK shows the scope you request in its authorization dialog. I'm not sure if it has a debug API endpoint, though.
