### ISSUE TITLE
АВТАР ПИДАРАС ОШИБКА 500

### ISSUE THREAD

**Issue by sergey-zero** [stevebest/passport-vkontakte#33]
АЛЁ.
СЛЫШ ДАУН
ЕСЛИ ВКАНТАКТИКЕ АТМЕНИТЬ ВХОД АШИПКА 500
С ДРУГИМ СОЦ СЕТЯМИ ВСЁ ОК. 

БЫСТРА БЛЯТЬ ИСПРАВИЛ АУ #34

**Comment by stevebest** [comment]
Никогда не думал, что мне придется применить функцию Report Abuse. Наслаждайтесь баном, уважаемый.

**Comment by MonoStas** [comment]
Трэш, угар. Никогда, тащемта, мир такого на гитхабе ещё не видывал. 
А вообще надо запретить гитхаб виндузятникам, тогда меньше школоты будет просачиваться. По-любому сидит с десктопной софтины и подсирает всем.
