### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Kalita-Roman** [stevebest/passport-vkontakte#35]
I try to use passport-vkontakte.
I have created my application in VK. 
I've set 
website URL: http://localhost
home domain: localhost
Trusted redirect URI: http://localhost/auth/vkontakte/callback.
I'm using localhost:80 for local server.
But when I send request to URI '/auth/vkontakte' ([https://github.com/stevebest/passport-vkontakte#authenticate-requests](url))
I get the error 
> XMLHttpRequest cannot load https://oauth.vk.com/authorize?response_type=code&redirect_uri=https...&scope=status%2Cemail%2Cfriends%2Cnotify&client_id=5675624. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access.

What do I wrong?

**Comment by stevebest** [comment]
Looks like you're trying to use `passport-vkontakte` in browser environment. That's not how it works.

In OAuth2 [Authorization Code Grant](https://tools.ietf.org/html/rfc6749#section-4.1), there are three parties involved:

1. VK,
2. user who has the VK account and a browser,
3. your app, which includes:
  1. a server-side Node.js app (this is where `passport-vkontakte` lives),
  2. optionally, a client side, which runs in user's browser.

If your app is client-only, you don't have to use this lib. In fact, you can't. There are official VK libraries for client-only authentication ("Login with VK" buttons and such). You can look them up yourself, I'm sick enough of VK dev site :)
