### ISSUE TITLE
InternalOAuthError: Failed to obtain access token

### ISSUE THREAD

**Issue by a1phaZ** [stevebest/passport-vkontakte#36]
Добрый день, пытаясь запустить пример из репозитория при авторизации выходит такой стек ошибок:

> InternalOAuthError: Failed to obtain access token
>    at Strategy.OAuth2Strategy._createOAuthError (D:\Work\sdb\node_modules\passport-oauth2\lib\strategy.js:370:17)
>    at D:\Work\sdb\node_modules\passport-oauth2\lib\strategy.js:166:45
>    at D:\Work\sdb\node_modules\oauth\lib\oauth2.js:177:18
>    at ClientRequest.<anonymous> (D:\Work\sdb\node_modules\oauth\lib\oauth2.js:148:5)
>    at emitOne (events.js:96:13)
>    at ClientRequest.emit (events.js:188:7)
>    at TLSSocket.socketErrorListener (_http_client.js:310:9)
>    at emitOne (events.js:96:13)
>    at TLSSocket.emit (events.js:188:7)
>    at emitErrorNT (net.js:1276:8)

В чем именно может быть проблема?

**Comment by Globik** [comment]
В течение часа токен живет. Потом убивается.
