### ISSUE TITLE
Cannot get email address

### ISSUE THREAD

**Issue by IvanMMM** [stevebest/passport-vkontakte#37]
Your documentation is little outdated and should be updated. 

Verify callback function can accept from 4 to 5 arguments and if you use 4 arguments you cannot get an email address and token lifetime even if it's set in scope and fields.

You should use
`function myVerifyCallbackFn(accessToken, refreshToken, params, profile, done){ ... }`
and you can get both 'email' and 'expires_in' from 'params' field.

**Comment by stevebest** [comment]
PRs are welcome

**Comment by IvanMMM** [comment]
Pulled #38

**Comment by stevebest** [comment]
I merged #38, is it OK to close this one?
