### ISSUE TITLE
passReqToCallback removing

### ISSUE THREAD

**Issue by gallyamb** [stevebest/passport-vkontakte#44]
Why are you removed support of the `options.passReqToCallback` introduced in https://github.com/stevebest/passport-vkontakte/commit/3873c1aa03347ca42e9258a6cce85a18f92db53e? This, in particular, discards the ability to connect existing user account with VK account.

**Comment by maximelkin** [comment]
bump request

**Comment by alexey2baranov** [comment]
+1
