### ISSUE TITLE
Publish new release

### ISSUE THREAD

**Issue by mayorandrew** [stevebest/passport-vkontakte#49]
As I can see, the latest release 0.3.2 published on github and npm does not include latest commits from the master branch. It would be great to publish the new version.

I currently use github link in my package.json file in order to get the latest version.

**Comment by Fxlr8** [comment]
As a quick fix you can pass `apiVersion: '5.8'` to strategy options

**Comment by Fxlr8** [comment]
nope, only `apiVersion: '5.89'` is working. OMG vk api is so unstable!
